border_width = 4
margin = [4, 4]
default_border_color = "#2e142d"
floating_border_color = "#DAA6F5"
focused_border_color = "#f0e3eb"


col1 = "#8935E5"
col2 = "#AF65D6"
col3 = "#9D59E6"
col4 = "#F1BEAB"
col5 = "#AF92D6"
col6 = "#DAA6F5"
col7 = "#f0e3eb"
col8 = "#a89ea4"
col9 = "#8935E5"
col10 = "#AF65D6"
col11 = "#9D59E6"
col12 = "#F1BEAB"
col13 = "#AF92D6"
col14 = "#DAA6F5"
col15 = "#f0e3eb"



background = "#2e142d"
foreground = "#f0e3eb"
