border_width = 4
margin = [4, 4]
default_border_color = "#090218"
floating_border_color = "#D49EDA"
focused_border_color = "#ebdfeb"


col1 = "#63456E"
col2 = "#B54073"
col3 = "#5B2495"
col4 = "#6D43AE"
col5 = "#BC43C6"
col6 = "#D49EDA"
col7 = "#ebdfeb"
col8 = "#a49ca4"
col9 = "#63456E"
col10 = "#B54073"
col11 = "#5B2495"
col12 = "#6D43AE"
col13 = "#BC43C6"
col14 = "#D49EDA"
col15 = "#ebdfeb"



background = "#090218"
foreground = "#ebdfeb"
